-- Nova tabela samo za skenirane fakture. Postojeće tabele se ne mijenjaju.
create table if not exists public.scan_queue (
  id bigint generated by default as identity primary key,
  imap_uid text not null unique,
  message_id text,
  filename text,
  received_at timestamptz not null default now(),
  status text not null default 'ready',
  error_message text,
  ai_result jsonb not null default '{}'::jsonb,
  processed boolean not null default false,
  processed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists scan_queue_pending_idx on public.scan_queue(processed, received_at desc);
alter table public.scan_queue enable row level security;
-- Browser ne pristupa ovoj tabeli direktno; koristi server-side API sa service role ključem.
